# Generated by Django 3.1.1 on 2020-10-16 10:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='idsinbloodinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('birthday', models.DateField(null=True)),
                ('height', models.CharField(max_length=20, null=True)),
                ('gender', models.BooleanField(max_length=10, null=True)),
                ('fcm_id', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('weight', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default='normal', max_length=20)),
                ('group', models.CharField(max_length=20, null=True)),
                ('unread_records1', models.CharField(max_length=20, null=True)),
                ('unread_records2', models.CharField(max_length=20, null=True)),
                ('unread_records3', models.CharField(max_length=20, null=True)),
                ('email_verfied', models.BooleanField(default=False, max_length=10, null=True)),
                ('privacy_policy', models.BooleanField(default=True, max_length=10, null=True)),
                ('must_change_password', models.BooleanField(default=False, max_length=10)),
                ('badge', models.CharField(max_length=20, null=True)),
                ('login_times', models.CharField(default=0, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('after_recording', models.CharField(max_length=20, null=True)),
                ('no_recording_for_a_day', models.CharField(max_length=20, null=True)),
                ('over_max_or_under_min', models.CharField(max_length=20, null=True)),
                ('after_meal', models.CharField(max_length=20, null=True)),
                ('unit_of_sugar', models.CharField(max_length=20, null=True)),
                ('unit_of_weight', models.CharField(max_length=20, null=True)),
                ('unit_of_height', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='sugarinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugar_delta_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_delta_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_morning_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_morning_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_evening_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_evening_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_before_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_before_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_after_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('sugar_after_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('systolic_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('systolic_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('diastolic_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('diastolic_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('pulse_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('pulse_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('weight_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('weight_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('bmi_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('bmi_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('body_fat_max', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('body_fat_min', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('patient', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='Denru.patient')),
            ],
        ),
        migrations.CreateModel(
            name='bloodinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1c', models.DecimalField(decimal_places=5, default=0, max_digits=20)),
                ('recorded_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Denru.patient')),
            ],
        ),
    ]
