# Generated by Django 3.1.1 on 2020-10-19 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typee', models.CharField(max_length=20, null=True)),
                ('hospitalname', models.CharField(max_length=20, null=True)),
                ('recorded_at', models.DateTimeField(null=True)),
                ('patient', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Denru.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='idsinbloodinfo',
        ),
    ]
