# Generated by Django 3.1.1 on 2020-10-20 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Denru', '0003_remove_checkcode_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='diabete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes_type', models.CharField(max_length=20, null=True)),
                ('oad', models.CharField(max_length=20, null=True)),
                ('insulin', models.CharField(max_length=20, null=True)),
                ('anti_hypertensives', models.CharField(max_length=20, null=True)),
                ('patient', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='Denru.patient')),
            ],
        ),
    ]
